//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlbumAndVideoEditingCharge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAlbumAndVideoEditingCharge()
        {
            this.tblQuotations = new HashSet<tblQuotation>();
        }
    
        public long AlbumAndVideoEditingChargesID { get; set; }
        public long CustomerID { get; set; }
        public Nullable<int> AlbumPage { get; set; }
        public string AlbumSize { get; set; }
        public Nullable<decimal> AlbumPrice { get; set; }
        public string AlbumPadSize { get; set; }
        public Nullable<decimal> AlbumPadPrice { get; set; }
        public Nullable<decimal> PhotoLEDFramePrice { get; set; }
        public Nullable<decimal> SpecialAlbum { get; set; }
        public Nullable<decimal> HDVideoDubbPendrivePrice { get; set; }
        public string Other { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public Nullable<bool> IsDisscount { get; set; }
        public Nullable<long> DiscountPercentage { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public Nullable<decimal> DiscountedAmount { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotation> tblQuotations { get; set; }
    }
}
