//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentHistory
    {
        public long PaymentHistoryID { get; set; }
        public Nullable<int> PhotographerID { get; set; }
        public Nullable<decimal> TotalPay { get; set; }
        public Nullable<decimal> RemainingPay { get; set; }
        public Nullable<System.DateTime> PaymetnDate { get; set; }
    
        public virtual tblPhotographer tblPhotographer { get; set; }
    }
}
