//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortfolioVisitor
    {
        public long PortfolioVisitorID { get; set; }
        public string CustomerName { get; set; }
        public string PortfolioVisitorName { get; set; }
        public string PortfolioVisitorEmail { get; set; }
        public string PortfolioVisitorPhoneNumber { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
    }
}
