//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotation
    {
        public int QuotationID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> NumberOfCinematographers { get; set; }
        public Nullable<int> NumberOfPhotographers { get; set; }
        public Nullable<int> NumberOfDrones { get; set; }
        public string SizeOfLEDScreen { get; set; }
        public Nullable<int> NumberOfLedScreens { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> IsDisccount { get; set; }
        public Nullable<int> DisscountPercentage { get; set; }
        public Nullable<decimal> AmmountAfterDisscount { get; set; }
        public Nullable<int> PercentageOfAdvancePayment { get; set; }
        public Nullable<int> PercentageOfPaymentAtEventDay { get; set; }
        public Nullable<int> PercentageOfPaymentAfterEvent { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
