//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotation
    {
        public long QuotationID { get; set; }
        public long AlbumAndVideoEditingChargesID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string FunctionName { get; set; }
        public Nullable<int> CandidCenematographers { get; set; }
        public Nullable<int> RegularCenematographers { get; set; }
        public Nullable<int> CandidPhotographer { get; set; }
        public Nullable<int> RegularPhotographer { get; set; }
        public Nullable<int> DSLR { get; set; }
        public Nullable<int> NumberOfDrones { get; set; }
        public string SizeOfLEDScreen { get; set; }
        public Nullable<int> NumberOfLedScreens { get; set; }
        public string Others { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblAlbumAndVideoEditingCharge tblAlbumAndVideoEditingCharge { get; set; }
    }
}
